### ISSUE TITLE
Demo Archive

### ISSUE THREAD

**Issue by ma1n** [BarberAlec/CSGO_Map_Model#1]
Hey, 
not really an issue and I don't know how active this project is still but I read this: 
"A problem currently being encountered is the lack of archive of DEMO files. As far as I am aware, no central archive is available. All DEMO files used in this project have been sourced through reddit where people have uploaded thier personal games for critics to analyse or from an analysis website which is no longer online. If anyone knows of a large archive, please let me know :)."

and wondered if you already know HLTV.org. 

https://www.hltv.org/results?content=vod <--- When you click on one of the matches you'll get to the matchpage where you can download the .dem files under "GOTV Demo". You can even sort after "stars" on the left to make sure only high quality games from good teams will be used in your project.

**Comment by BarberAlec** [comment]
Hi ma1n, this project has been a little on the back burner, but I am coming back to it again now! In fact, I have just found that the library I was using for parsing no longer works and is not being updated :/. I am now moving over to another parser built by Valve.

Yea, I did have a problem with this alright. Thank you for pointing that out, I did not see this before. I recently also found another site esea which have some demos also. (https://play.esea.net/index.php?s=league&d=schedule&refresh_interval=30000&date=2020-06-23&region_id=2&game_id=25&division_level=all). 

Thank you for getting in contact!
